### ISSUE TITLE
Data & metadata structuring

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#28]
**Description**
Our users want to be able to enter config and pages metadata in a structured way.
Popular choices include JSON, YAML and TOML.

**Task**
- [x] Decide on what format to use
- [x] Explore the possbility of supporting multiple formats

**Comment by Lothindir** [comment]
The metadata block in a Markdown file must be at the beginning of the file. It begins with `---` and ends with `...`.
Example: 
```md
---
title:  'This is the title: it contains a colon'
author:
- name: Author One
  affiliation: University of Somewhere
- name: Author Two
  affiliation: University of Nowhere
tags: [nothing, nothingness]
abstract: |
  This is the abstract.

  It consists of two paragraphs.
...
# Title 1
Lorem Ipsum...
```

**Comment by Lothindir** [comment]
The defacto format for metadata will be YAML, for now no other formats will be supported.

**Comment by MaximGY** [comment]
We agreed not to look into supporting multiple formats.
