### ISSUE TITLE
Pages format

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#30]
**Description**
Each page must have some kind of header containing metadata, a separator, and the data of the page.  We need to discuss the layout details of these files.

**Task**
- [x] Format of metadata
- [x] Format of data
- [x] Separator

**Comment by MaximGY** [comment]
See https://github.com/dil-classroom/projet-marzullo_matias_monti_golay_perrenoud/issues/28#issuecomment-1076422170

**Comment by Lothindir** [comment]
Replied in https://github.com/dil-classroom/projet-marzullo_matias_monti_golay_perrenoud/issues/28#issuecomment-1076422170
