### ISSUE TITLE
Implement `build` command

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#35]
**Description**
This command should have a semantic similar to the one described in #34, replacing `init` with `build`. It should, in the directory passed as a parameter, create a `build` directory which will contain the resulting site. The site is to be built using the sources and the config file in the directory mentioned above.

**Task**
Add a list of optional tasks
- [x] #32
- [x] #28 
- [x] #29 
- [x] Use a library to convert pages to actual HTML
- [x] Use the config file somehow

**Time required:**
- Optimistic: 30 minutes
- Pessimistic: 02h00
- Expected: 01h00

**Comment by Lothindir** [comment]
Lib for parsing JSON/YAML/...: https://www.tutorialspoint.com/jackson/index.htm

**Comment by MrDaves24** [comment]
Checking lib https://products.aspose.com/words/java/conversion/md-to-html/

**Comment by MrDaves24** [comment]
Using lib https://github.com/commonmark/commonmark-java
