### ISSUE TITLE
Cannot find launch4j dependency

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#45]
**Description**
Got error `Cannot resolve plugin com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:<unknown>` on `main` branch when opening the project

**Comment by MaximGY** [comment]
@Lothindir are we missing a config somewhere ?

**Comment by MaximGY** [comment]
Oddly enough the building goes fine, i can run the `.jar` and the executable and it works as expected, but IntelliJ says that the package cant be found... 

![image](https://user-images.githubusercontent.com/36033687/160869444-8ab7f0f0-7d94-4949-9a4d-b637b9ece4ab.png)

Its not that important so I think I'll close the issue and post a fix if I find one later on.

**Comment by Lothindir** [comment]
I think it is due to the way Maven works, and IntelliJ cannot physically find the package on the machine. I do not have this problem on VS Code.
