### ISSUE TITLE
Site previewing

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#52]
**Description**
As a user, I want to be able to preview my site before deploying it. I should be able to do this using the app, with a command like `hyde serve /path/to/my/site`.

**Task**
- [x] Decide on a HTTP server
- [x] Implement `serve` command

Time required:

- Optimistic: 30 min
- Pessimistic: 1h30
- Expected: 45 min

**Comment by JoelMatias** [comment]
Il a été décidé que nous ouvrirons le fichier html via le navigateur par défaut pour avoir une preview du site.
