### ISSUE TITLE
Implement file inlcudes

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#55]
**Description**
We need a way to load files storing redundant HTML to be used in other files.

**Task**
- [x] #72
- [ ] Implement file content injection

**Time estimates**
- Required: 2h
- Optimistic: 1h
- Pessimistic: 3h
- Actual:

**Comment by MrDaves24** [comment]
Files to include will be on folder "template" as per PR #63 !
