### ISSUE TITLE
Build functionnality fixes

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#81]
# Description
Fix the multiple issues and code-smell of the Build command, especially in the function "build"

# Tasks
- The function build only handle md files, it should copy everything
- To build the full project, you shouldn't have to give an empty string... It's a code-smell
- The build function shouldn't wait for a "file" but for a path

# Time estimation
- Expected : 30min
- Optimistic : 20min
- Pessimistic : 1h

**Time taken:**
4h

**Comment by Lothindir** [comment]
Fixed by #83
